name: PXD030304
dataset_path: "../data/processed/PXD030304/PXD030304_no_control_multi_peptide_50pct_tissue/small/PXD030304_no_control_multi_peptide_50pct_tissue.csv"
normalizer: "minmax"
log_transform: True