n_runs: 1
initial_seed: 42

validation_strategy:
  - name: "groupkfold"
    num_folds: 2
    miss_rate: 0.10
    holdout_tissues: ["Haematopoietic and Lymphoid", "Lung"]

models:
  - name: tissue_mean