n_runs: 1
initial_seed: 42

validation:
  name: "holdout"
  target_missing: [0.20]

models:
  - name: protogain
    model_cfg_path: "../configs/model/protogain.yaml"
    training_cfg_path: "../configs/train/gain_train.yaml"