n_runs: 1
initial_seed: 42

validation:
  name: "holdout"
  missing_levels: [0.30]

models:
  - name: protogain
    model_cfg_path: "../configs/model/protogain.yaml"
    training_cfg_path: "../configs/train/gain_train.yaml"