n_runs: 1
initial_seed: 42

validation:
  name: "holdout"
  missing_levels: [0.10]

models:
  - name: autoencoder
    model_cfg_path: "../configs/model/ae.yaml"
    training_cfg_path: "../configs/train/ae_train.yaml"