n_runs: 1
initial_seed: 42

validation:
  name: "holdout"
  target_missing: [0.20]

models:
  - name: autoencoder
    model_cfg_path: "../configs/model/ae.yaml"
    training_cfg_path: "../configs/train/ae_train.yaml"