n_runs: 1
initial_seed: 42

validation_strategy:
  - name: "group-k-fold"
    num_folds: 2

models:
  - name: protogain
    model_config: "../configs/model/protogain.yaml"
    train_config: "../configs/train/train.yaml"