missingness_levels: [0.10]
n_runs: 1 # number of runs for each missingness level
initial_seed: 44

validation_strategy: 
  - name: "k-fold"
    num_folds: 5

models:
  # - name: protogain
  #   model_config: "../configs/model/protogain.yaml"
  #   train_config: "../configs/train/train.yaml"
  - name: missForest
    model_config: "../configs/model/missforest.yaml"