num_epochs: 100
patience: 20
min_delta: 1e-6
batch_size: 1000

generator_optimizer:
  lr: 1.0e-3
  weight_decay: 1e-4
generator_scheduler:
  step: 100
  gamma: 0.5

discriminator_optimizer:
  lr: 1.0e-5
  weight_decay: 0.5
discriminator_scheduler:
  step: 100
  gamma: 0.5

alpha: 10
hint_rate: 0.5